openapi: 3.1.0
info:
  title: Github Issue API Mock
  description: ''
  version: 1.0.0
servers:
  - url: http://localhost:8787/github
    description: 'Localhost dev environment'
paths:
  /issue:
    get:
      operationId: loadAllIssues
      tags:
        - Issue
      responses:
        '200':
          description: An array of all Github issues
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Issue'
      summary: Endpoint for loading issues
      description: >-
        Retrieves all the issues that are currently existing.
      parameters: []
      deprecated: false
    post:
      operationId: createIssue
      tags:
        - Issue
      summary: Endpoint for creating a new issue
      description: >-
        Creating a new issue by providing all attributes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Issue'
      responses:
        '200':
          description: The just created issue
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Issue'
    put:
      operationId: updateIssue
      tags:
        - Issue
      summary: Endpoint for updating an existing issue
      description: >-
        Update an existing issue by providing all attributes including the unchanged ones.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Issue'
      responses:
        '200':
          description: An array of all the issues from Gitlab
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Issue'
components:
  schemas:
    Issue:
      type: object
      description: ''
      deprecated: false
      properties:
        id:
          type: string
        name:
          type: string
        body:
          type: string
        closed:
          type: boolean
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes: {}
security: []
tags: []
