image: gitpod/workspace-bun

tasks:
  - name: Install dependencies
    # TODO: remove upgrade when workspace image is up to date
    init: |
      bun upgrade
      bun install
    command: |
      bun upgrade
      gp sync-done install
