/**
 * `@mediator/db` — the mediator database layer: a typed Drizzle instance over
 * the compose Postgres, a transaction helper, the migration runner, the Phase-1
 * schema, and repositories that accept/return `@mediator/domain` types through
 * explicit mappers (Drizzle's inferred optionality stays inside this package).
 */
export { closeDb, createDb, tx } from "./client.js";
export type { Database, DbHandle, DbTransaction, TransactionScope } from "./client.js";
export { InvalidDatabaseUrlError, MissingDatabaseUrlError, resolveDatabaseUrl } from "./env.js";
export { MIGRATIONS_FOLDER, runMigrations } from "./migrate.js";

// Schema (tables, pg enums, ref-kind vocabulary).
export {
  DETECTION_JOB_STATUSES,
  ORDERING_QUEUE_STATUSES,
  RESOURCE_BINDING_REF_KINDS,
  adapterBinding,
  adapterBindingRoleEnum,
  adapterBindingStatusEnum,
  adapterEndpoint,
  adapterEndpointStatusEnum,
  apiSpec,
  apiSpecRoleEnum,
  apiSpecStatusEnum,
  approvedMapping,
  approvedMappingStatusEnum,
  auditLog,
  auditLogStatusEnum,
  auditLogTypeEnum,
  conflictPolicyEnum,
  credential,
  credentialTypeEnum,
  detectionJobStatusEnum,
  eventOutbox,
  fieldMapping,
  graphEdge,
  graphEdgeTypeEnum,
  mappingDecisionEnum,
  mappingDetectionJob,
  mappingPhaseEnum,
  mappingProposal,
  mappingProposalItem,
  mappingProposalItemKindEnum,
  mappingProposalStatusEnum,
  mappingVariantEnum,
  operationActionEnum,
  operationMapping,
  orderingQueue,
  orderingQueueStatusEnum,
  parameterMapping,
  processedEvent,
  recordLink,
  recordLinkEstablishedByEnum,
  recordLinkStatusEnum,
  recordLinkTombstoneReasonEnum,
  registeredApp,
  registeredAppStatusEnum,
  resourceBinding,
  resourceBindingRef,
  resourceBindingRefKindEnum,
  reviewStateEnum,
  syncFieldState,
  syncFieldStateSideEnum,
  syncFieldStateStatusEnum,
  syncRule,
  syncRuleStatusEnum,
  transformKindEnum,
  type DetectionJobStatus,
  type OrderingQueueStatus,
  type ResourceBindingRefKind,
} from "./schema.js";

// Mappers + their domain-facing types (row/insert types stay internal to the
// mapper modules but the projection/patch types are part of the repo surface).
export {
  mapAdapterBindingRow,
  mapAdapterEndpointRow,
  mapApiSpecRow,
  mapApprovedMappingRow,
  mapAuditLogRow,
  mapCredentialMetadataRow,
  mapEventOutboxRow,
  mapFieldMappingRow,
  mapGraphEdgeRow,
  mapMappingProposalItemRow,
  mapMappingProposalRow,
  mapOperationMappingRow,
  mapParameterMappingRow,
  mapRecordLinkRow,
  mapRegisteredAppRow,
  mapResourceBinding,
  mapSyncFieldStateRow,
  mapSyncRuleRow,
  toAdapterBindingInsert,
  toAdapterEndpointInsert,
  toApiSpecInsert,
  toApprovedMappingInsert,
  toAuditLogInsert,
  toCredentialInsert,
  toEventOutboxInsert,
  toFieldMappingInsert,
  toGraphEdgeInsert,
  toMappingProposalInsert,
  toMappingProposalItemInsert,
  toOperationMappingInsert,
  toParameterMappingInsert,
  toRecordLinkInsert,
  toRegisteredAppInsert,
  toResourceBindingInsert,
  toResourceBindingRefInserts,
  toResourceBindingRefUpdate,
  toSyncFieldStateInsert,
  toSyncRuleInsert,
  type ConfirmableRefPatch,
  type CredentialMetadata,
  type MappingProposalInsert,
  type MappingProposalItemInsert,
  type MappingProposalItemRow,
  type MappingProposalRow,
  type OutboxInsert,
  type OutboxRecord,
  type RecordLinkInsert,
  type RecordLinkRow,
  type ResourceBindingRefPatch,
  type SyncFieldStateInsert,
  type SyncFieldStateRow,
} from "./mappers/index.js";

// Repositories.
export {
  ApiSpecRepository,
  ApprovedMappingRepository,
  AuditLogRepository,
  CredentialRepository,
  DetectionJobRepository,
  DownstreamArtifactRepository,
  EventOutboxRepository,
  MappingArtifactsRepository,
  MappingProposalRepository,
  OrderingQueueRepository,
  ProcessedEventRepository,
  RecordLinkRepository,
  RegisteredAppRepository,
  ResourceBindingRepository,
  SyncFieldStateRepository,
  type ClaimedDetectionJob,
  type ClaimedQueueEntry,
  type ClaimParams,
  type DetectionJob,
  type DetectionJobEnqueueOps,
  type DetectionJobWorkerOps,
  type DownstreamArtifactOps,
  type MappingArtifacts,
  type OrderingQueueDrainQuery,
  type OrderingQueueEnqueueOps,
  type OrderingQueueEntry,
  type OrderingQueueWorkerOps,
  type OutboxOps,
  type ProcessedEventOps,
  type RecordLinkSideRef,
  type RecordLinkStore,
  type SyncFieldStateStore,
} from "./repositories/index.js";
