/**
 * `@mediator/db` — the mediator database layer: a typed Drizzle instance over
 * the compose Postgres, a transaction helper, the migration runner, the Phase-1
 * schema, and repositories that accept/return `@mediator/domain` types through
 * explicit mappers (Drizzle's inferred optionality stays inside this package).
 */
export { closeDb, createDb, tx } from "./client.js";
export type { Database, DbHandle, DbTransaction, TransactionScope } from "./client.js";
export { InvalidDatabaseUrlError, MissingDatabaseUrlError, resolveDatabaseUrl } from "./env.js";
export { MIGRATIONS_FOLDER, runMigrations } from "./migrate.js";

// Schema (tables, pg enums, ref-kind vocabulary).
export {
  CROSS_SCOPE_SCOPE_KEY,
  DETECTION_JOB_STATUSES,
  ORDERING_QUEUE_STATUSES,
  RESOURCE_BINDING_REF_KINDS,
  adapterBinding,
  adapterBindingRoleEnum,
  adapterBindingStatusEnum,
  adapterEndpoint,
  adapterEndpointStatusEnum,
  adapterRequestCauseEnum,
  adapterWriteOutcome,
  adapterWriteOutcomeStatusEnum,
  aggregationStrategyEnum,
  apiSpec,
  apiSpecRoleEnum,
  apiSpecStatusEnum,
  approvedMapping,
  approvedMappingStatusEnum,
  auditLog,
  auditLogStatusEnum,
  auditLogTypeEnum,
  backfillModeEnum,
  backfillStatusEnum,
  conflictPolicyEnum,
  credential,
  credentialTypeEnum,
  deletePropagationEnum,
  detectionJobStatusEnum,
  endpointStrictnessEnum,
  eventOutbox,
  fieldMapping,
  graphEdge,
  graphEdgeTypeEnum,
  mappingDecisionEnum,
  mappingDetectionJob,
  mappingPhaseEnum,
  mappingProposal,
  mappingProposalItem,
  mappingProposalItemKindEnum,
  mappingProposalStatusEnum,
  mappingVariantEnum,
  operationActionEnum,
  operationMapping,
  orderingQueue,
  orderingQueueStatusEnum,
  parameterMapping,
  parkedConflict,
  parkedConflictKindEnum,
  parkedConflictResolutionChoiceEnum,
  parkedConflictStatusEnum,
  pollScopeModeEnum,
  pollScopeState,
  pollSnapshot,
  processedEvent,
  recordLink,
  recordLinkEstablishedByEnum,
  recordLinkStatusEnum,
  recordLinkTombstoneReasonEnum,
  registeredApp,
  registeredAppStatusEnum,
  resourceBinding,
  resourceBindingRef,
  resourceBindingRefKindEnum,
  reviewStateEnum,
  scopeCorrespondence,
  scopeLink,
  syncFieldState,
  syncFieldStateSideEnum,
  syncFieldStateStatusEnum,
  syncRule,
  syncRuleStatusEnum,
  targetDriftCheckEnum,
  transformKindEnum,
  type AdditiveDeltaScope,
  type DetectionJobScope,
  type DetectionJobStatus,
  type OrderingQueueStatus,
  type ReReviewResourcePair,
  type ReReviewScope,
  type ReReviewStaleMappingScope,
  type ResourceBindingRefKind,
} from "./schema.js";

// Mappers + their domain-facing types (row/insert types stay internal to the
// mapper modules but the projection/patch types are part of the repo surface).
export {
  mapAdapterBindingRow,
  mapAdapterEndpointRow,
  mapAdapterWriteOutcomeMetadataRow,
  mapAdapterWriteOutcomeRow,
  mapApiSpecRow,
  mapApprovedMappingRow,
  mapAuditLogRow,
  mapCredentialMetadataRow,
  mapEventOutboxRow,
  mapFieldMappingRow,
  mapGraphEdgeRow,
  mapMappingProposalItemRow,
  mapMappingProposalRow,
  mapOperationMappingRow,
  mapParameterMappingRow,
  mapParkedConflictRow,
  mapRecordLinkRow,
  mapRegisteredAppRow,
  mapResourceBinding,
  mapSyncFieldStateRow,
  mapSyncRuleRow,
  toAdapterBindingInsert,
  toAdapterEndpointInsert,
  toAdapterWriteOutcomeInsert,
  toApiSpecInsert,
  toApprovedMappingInsert,
  toAuditLogInsert,
  toCredentialInsert,
  toEventOutboxInsert,
  toFieldMappingInsert,
  toGraphEdgeInsert,
  toMappingProposalInsert,
  toMappingProposalItemInsert,
  toOperationMappingInsert,
  toParameterMappingInsert,
  toParkedConflictInsert,
  toRecordLinkInsert,
  toRegisteredAppInsert,
  toResourceBindingInsert,
  toResourceBindingRefInserts,
  toResourceBindingRefUpdate,
  toSyncFieldStateInsert,
  toSyncRuleInsert,
  type ConfirmableRefPatch,
  type CredentialMetadata,
  type MappingProposalInsert,
  type MappingProposalItemInsert,
  type MappingProposalItemRow,
  type MappingProposalRow,
  type OutboxInsert,
  type OutboxRecord,
  type ParkedConflictInsert,
  type ParkedConflictRow,
  type RecordLinkInsert,
  type RecordLinkRow,
  type ResourceBindingRefPatch,
  type ScopePathBindingPatch,
  type SourceScopeRefPatch,
  type SyncFieldStateInsert,
  type SyncFieldStateRow,
} from "./mappers/index.js";

// Repositories.
export {
  AdapterCompositionRepository,
  AdapterWriteOutcomeRepository,
  ApiSpecRepository,
  ApprovedMappingRepository,
  AuditLogRepository,
  CredentialRepository,
  DetectionJobRepository,
  DownstreamArtifactRepository,
  EventOutboxRepository,
  MappingArtifactsRepository,
  MappingProposalRepository,
  OrderingQueueRepository,
  ParkedConflictRepository,
  PollScopeStateRepository,
  PollSnapshotRepository,
  ProcessedEventRepository,
  RecordLinkRepository,
  RegisteredAppRepository,
  ResourceBindingRepository,
  ScopeCorrespondenceRepository,
  ScopeLinkRepository,
  SyncFieldStateRepository,
  SyncRuleRepository,
  type AdapterEdgeMemberFact,
  type AdapterWriteOutcomeOps,
  type ApplyCompositionInput,
  type ApplyCompositionResult,
  type ClaimedDetectionJob,
  type ClaimedQueueEntry,
  type ClaimParams,
  type CompositionBindingConfig,
  type CompositionEndpointConfig,
  type DetectionJob,
  type DetectionJobEnqueueOps,
  type DetectionJobWorkerOps,
  type DownstreamArtifactOps,
  type GraphEdgeStatusUpdate,
  type MappingArtifacts,
  type OrderingQueueDeadLetterOps,
  type OrderingQueueDrainQuery,
  type OrderingQueueEnqueueOps,
  type OrderingQueueEntry,
  type OrderingQueueWorkerOps,
  type OutboxOps,
  type ParkedConflictResolution,
  type ParkedConflictStore,
  type ParkedWriteContext,
  type ParkedWriteEntry,
  type ReactivateParkedResult,
  type PollCandidate,
  type PollScopeStateAdvance,
  type PollScopeStateRecord,
  type PollSnapshotRecord,
  type ProcessedEventOps,
  type EstablishScopeLinkResult,
  type RecordLinkSide,
  type RecordLinkSideRef,
  type RecordLinkStore,
  type AdapterRequestQuery,
  type ScopeLinkSideRef,
  type ScopeLinkStore,
  type SyncEdgeMemberFact,
  type SyncEventQuery,
  type SyncFieldStateStore,
  type SyncRuleAdvance,
  type SyncRuleConfigPatch,
  type SyncRuleEnableTransition,
} from "./repositories/index.js";
