/**
 * `@mediator/contracts` — the operator-API request/response DTO schemas (Zod)
 * and their inferred types, shared by the backend routes and the frontend client
 * with no codegen.
 *
 * DTOs are kept distinct from `@mediator/domain` entities wherever the wire shape
 * differs: a domain `Date` becomes an ISO-8601 string, `ApiSpec.rawDocument` is
 * never exposed by a metadata/list DTO, and credential material / `encryptedPayload`
 * appear in **no** response schema (CR-2). The package depends only on
 * `@mediator/domain` (IR + enums + shared sub-shapes) and `zod`, so the frontend
 * can import it without pulling in any backend/persistence code.
 */

export {
  RESOURCE_BINDING_REF_KINDS,
  errorResponseSchema,
  isoDateTimeSchema,
  resourceBindingRefKindSchema,
  validationIssueSchema,
  type ErrorResponse,
  type ResourceBindingRefKind,
  type ValidationIssue,
} from "./common.js";

export {
  credentialMaterialDtoSchema,
  credentialSecretDtoSchema,
  type CredentialMaterialDto,
  type CredentialSecretDto,
} from "./credentials.js";

export {
  cutoverAdapterTokenResponseSchema,
  issueAdapterTokenResponseSchema,
  type CutoverAdapterTokenResponse,
  type IssueAdapterTokenResponse,
} from "./adapter-token.js";

export {
  apiSpecMetadataDtoSchema,
  appListResponseSchema,
  appSpecsResponseSchema,
  openApiDocumentSchema,
  registerAppRequestSchema,
  registerAppResponseSchema,
  registerSpecRequestSchema,
  registeredAppDtoSchema,
  type ApiSpecMetadataDto,
  type AppListResponse,
  type AppSpecsResponse,
  type RegisterAppRequest,
  type RegisterAppResponse,
  type RegisterSpecRequest,
  type RegisteredAppDto,
} from "./apps.js";

export {
  irResponseSchema,
  previewParseRequestSchema,
  previewParseResponseSchema,
  resourceGroupSummarySchema,
  updateAnalysisExclusionsRequestSchema,
  updateAnalysisExclusionsResponseSchema,
  type IrResponse,
  type PreviewParseRequest,
  type PreviewParseResponse,
  type ResourceGroupSummary,
  type UpdateAnalysisExclusionsRequest,
  type UpdateAnalysisExclusionsResponse,
} from "./specs.js";

export {
  resourceBindingDtoSchema,
  resourceBindingRefDtoSchema,
  resourceBindingScopeConstantDtoSchema,
  resourceBindingScopeDtoSchema,
  resourceBindingScopeRecordDerivedDtoSchema,
  resourceBindingSourceScopeRefDtoSchema,
  resourceBindingsResponseSchema,
  sourceScopeComponentPatchSchema,
  updateResourceBindingRefRequestSchema,
  updateResourceBindingRequestSchema,
  updateResourceBindingResponseSchema,
  updateScopeBindingRequestSchema,
  updateScopeConstantBindingRequestSchema,
  updateScopeRecordDerivedBindingRequestSchema,
  updateSourceScopeRefRequestSchema,
  type ResourceBindingDto,
  type ResourceBindingRefDto,
  type ResourceBindingScopeConstantDto,
  type ResourceBindingScopeDto,
  type ResourceBindingScopeRecordDerivedDto,
  type ResourceBindingScopeScopeLinkDto,
  type ResourceBindingSourceScopeRefDto,
  type ResourceBindingsResponse,
  type SourceScopeComponentPatch,
  type UpdateResourceBindingRefRequest,
  type UpdateResourceBindingRequest,
  type UpdateResourceBindingResponse,
  type UpdateScopeBindingRequest,
  type UpdateScopeConstantBindingRequest,
  type UpdateScopeRecordDerivedBindingRequest,
  type UpdateScopeScopeLinkBindingRequest,
  type UpdateSourceScopeRefRequest,
} from "./resource-bindings.js";

export {
  sessionResponseSchema,
  sessionRoleSchema,
  type SessionResponse,
  type SessionRole,
} from "./session.js";

export {
  ambiguousMatchDtoSchema,
  ambiguousMatchListResponseSchema,
  configureSyncRuleRequestSchema,
  configureSyncRuleResponseSchema,
  confirmScopeIdentityKeyRequestSchema,
  confirmScopeIdentityKeyResponseSchema,
  createRecordLinkRequestSchema,
  createRecordLinkResponseSchema,
  createScopeLinkRequestSchema,
  createScopeLinkResponseSchema,
  deadLetterQueueResponseSchema,
  deadLetterWriteDtoSchema,
  disableSyncRuleResponseSchema,
  enableSyncRuleRequestSchema,
  enableSyncRuleResponseSchema,
  enablementDegradationDtoSchema,
  enablementRequirementDtoSchema,
  fieldConflictPolicyDtoSchema,
  parkedConflictDtoSchema,
  parkedConflictListResponseSchema,
  parkedContainerLinkDtoSchema,
  parkedContainerLinkListResponseSchema,
  pollRunOutcomeDtoSchema,
  pollerLagDtoSchema,
  recordLinkDtoSchema,
  replayParkedWriteResponseSchema,
  resolveParkedConflictRequestSchema,
  resolveParkedConflictResponseSchema,
  scopeCorrespondenceDtoSchema,
  scopeIdentityKeyDerivationResponseSchema,
  scopeLinkCandidateContextResponseSchema,
  scopeLinkDtoSchema,
  syncEventDtoSchema,
  syncEventListResponseSchema,
  syncEventQuerySchema,
  syncRuleListResponseSchema,
  syncRuleResourcePairDtoSchema,
  syncRuleResourceSideDtoSchema,
  syncRuleStatusDtoSchema,
  triggerPollResponseSchema,
  unlinkRecordResponseSchema,
  unlinkScopeLinkResponseSchema,
  type AmbiguousMatchDto,
  type AmbiguousMatchListResponse,
  type ConfigureSyncRuleRequest,
  type ConfigureSyncRuleResponse,
  type ConfirmScopeIdentityKeyRequest,
  type ConfirmScopeIdentityKeyResponse,
  type CreateRecordLinkRequest,
  type CreateRecordLinkResponse,
  type CreateScopeLinkRequest,
  type CreateScopeLinkResponse,
  type DeadLetterQueueResponse,
  type DeadLetterWriteDto,
  type DisableSyncRuleResponse,
  type EnableSyncRuleRequest,
  type EnableSyncRuleResponse,
  type EnablementDegradationDto,
  type EnablementRequirementDto,
  type FieldConflictPolicyDto,
  type ParkedConflictDto,
  type ParkedConflictListResponse,
  type ParkedContainerLinkDto,
  type ParkedContainerLinkListResponse,
  type PerScopeRunResultDto,
  type PollRunOutcomeDto,
  type PollerLagDto,
  type RecordLinkDto,
  type ReplayParkedWriteResponse,
  type ResolveParkedConflictRequest,
  type ResolveParkedConflictResponse,
  type ScopeCorrespondenceDto,
  type ScopeIdentityKeyDerivationResponse,
  type ScopeLinkCandidateContextResponse,
  type ScopeLinkDto,
  type SyncEventDto,
  type SyncEventListResponse,
  type SyncEventQuery,
  type SyncRuleListResponse,
  type SyncRuleResourcePairDto,
  type SyncRuleResourceSideDto,
  type SyncRuleStatusDto,
  type TriggerPollResponse,
  type UnlinkRecordResponse,
  type UnlinkScopeLinkResponse,
} from "./sync.js";

export {
  analyzeResourcePairRequestSchema,
  analyzeResourcePairResponseSchema,
  approveProposalRequestSchema,
  approveProposalResponseSchema,
  approvedMappingRefDtoSchema,
  identityKeyConfirmationSchema,
  mappingProposalDetailResponseSchema,
  mappingProposalItemDtoSchema,
  mappingProposalListResponseSchema,
  mappingProposalSummaryDtoSchema,
  operationOverrideSchema,
  proposalShortlistDtoSchema,
  recordProposalItemDecisionRequestSchema,
  recordProposalItemDecisionResponseSchema,
  type AnalyzeResourcePairRequest,
  type AnalyzeResourcePairResponse,
  type ApproveProposalRequest,
  type ApproveProposalResponse,
  type ApprovedMappingRefDto,
  type IdentityKeyConfirmationDto,
  type MappingProposalDetailResponse,
  type MappingProposalItemDto,
  type MappingProposalListResponse,
  type MappingProposalSummaryDto,
  type OperationOverrideDto,
  type ProposalShortlistDto,
  type RecordProposalItemDecisionRequest,
  type RecordProposalItemDecisionResponse,
} from "./mapping-proposals.js";
